# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- main

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dynamoDbImage: 'amazon/dynamodb-local'

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  displayName: 'Install .NET 7.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: |
      **/Azure1.csproj
      **/Azure2.csproj
      **/UITest.csproj
  displayName: Restore PRSQRL_Nest Nuget Packages

- task: DotNetCoreCLI@2
  displayName: 'Build Projects'
  inputs:
    command: 'build'
    projects: |
      **/Azure1.csproj
      **/Azure2.csproj
      **/UITest.csproj
    arguments: '--configuration $(BuildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'Publish Azure1'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    projects: '**/Azure1.csproj'
    arguments: -c $(BuildConfiguration) -o release

- task: DotNetCoreCLI@2
  displayName: 'Publish Azure2'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    projects: '**/Azure2.csproj'
    arguments: -c $(BuildConfiguration) -o release

# - task: PowerShell@2
#   displayName: Run Azure1
#   inputs:
#     targetType: 'inline'
#     script: |
#       Start-Process -FilePath "Azure1.exe" -WorkingDirectory "release\Azure1" -ArgumentList "--urls=https://localhost:7005"
    
# - task: PowerShell@2
#   displayName: Rune Azure2
#   inputs:
#     targetType: 'inline'
#     script: |
#       Start-Process -FilePath "Azure2.exe" -WorkingDirectory "release\Azure2" -ArgumentList "--urls=https://localhost:7225"

- task: CmdLine@2
  inputs:
    script: 'google-chrome --version'

- task: CmdLine@2
  inputs:
    script: './release/Azure1/Azure1 --urls=https://localhost:7005 &'
- task: CmdLine@2
  inputs:
    script: './release/Azure2/Azure2 --urls=https://localhost:7225 &'

- task: DotNetCoreCLI@2
  displayName: 'Run Automated Unit Tests' 
  inputs:
    command: 'test'
    projects: '**/UITest.csproj'
    arguments: '--no-restore'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  displayName: Run DynamoDB container
  inputs:
    command: login
    containerRegistry: 'DockerRegistry'

- script: |
    docker run --name mycontainer -d -p 8000:8000 $(dynamoDbImage)