on: push

env:
    AWS_REGION: us-east-2

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Azure1
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Azure1.sln

    - name: Build
      run: dotnet build --no-restore Azure1.sln

    - name: Publish
      run: dotnet publish **/*Azure1.csproj -c Release -o release1
      
    - name: Publish Azure2
      run: dotnet publish **/*Azure2.csproj -c Release -o release2

      # web api expects appsettings in the directory its run from
      # not the directory that it exists in so we have to copy it here
      # to ensure that it's found and read since we are running it from it's publish directory
    # - name: Move appsettings workaround
      # run: cp ./release/appsettings.json ./appsettings.json
      
    - name: where am i
      run: ls -a release1

    - name: Run Azure1
      run: ./release1/Azure1 --urls=https://localhost:7005 &
      
    - name: Run Azure2
      run: ./release2/Azure2 --urls=https://localhost:7225 &

    - name: Test
      run: dotnet test **/*UITest.csproj --no-build --no-restore --verbosity normal